apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: southamerica-west1-docker.pkg.dev/tienda-microservicios-462023/image-registry/payments-ms
        name: payments-ms
        env:
        - name: PORT
          value: "3003"
        - name: NATS_SERVERS
          value: nats://nats:4222
        - name: STRIPE_SUCCESS_URL
          value: "http://172.23.26.82:32534/payments/success"
        - name: STRIPE_CANCEL_URL
          value: "http://172.23.26.82:32534/payments/cancel"
        - name: STRIPE_PUBLIC
          value: pk_test_51RQZJ3DFsTwOFt1XeGjtKTcQhOdW8dc9PbiQhznr9TMY9Ixuz4HJyv0TJusLu1Pmg5ZF1kiVKMrxHJNK6y3eq9rX00a4bHhKPf
        - name: STRIPE_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_secret
        - name: STRIPE_ENDPOINT_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_endpoint_secret
        resources: {}
status: {}
