apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: products-ms
  name: products-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: products-ms
    spec:
      containers:
      - image: southamerica-west1-docker.pkg.dev/tienda-microservicios-462023/image-registry/products-ms
        name: products-ms
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: NATS_SERVERS
          value: nats://nats:4222
        - name: DATABASE_URL
          value: file:./dev.db
        - name: NODE_ENV
          value: "production"
        resources: {}
status: {}
